### ISSUE TITLE
Unable to parse response, XML is expected

### ISSUE THREAD

**Issue by elier** [IBM-Bluemix-Docs/cloud-object-storage-infrastructure#5]
The latest AWS CLI does not work with IBM Cloud Object Storage S3 API.

The following command return: Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. 

`aws --endpoint-url=https://{endpoint} s3 ls`

The response from the API is in JSON and I believe the AWS CLI only support XML.

Ref: https://cloud.ibm.com/docs/infrastructure/cloud-object-storage-infrastructure?topic=cloud-object-storage-infrastructure-using-a-cli

**Comment by nglange** [comment]
The underlying boto3 library converts to XML.  This was an issue with character encoding that has since been fixed.  Thanks!
